name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build App
        run: ./scripts/buildprod.sh

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Build and push to GCP"
        run: "gcloud builds submit --tag us-east4-docker.pkg.dev/notley-400302/notely-ar-repo/thegreatestgiant/notely:latest ."

      - name: "Deploy to Cloud Run"
        run: gcloud run deploy notely --image us-east4-docker.pkg.dev/notley-400302/notely-ar-repo/thegreatestgiant/notely:latest --region us-east4 --allow-unauthenticated --project notley-400302 --max-instances=4
